name: Performance Profiling

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'  # Trigger on all branches

jobs:
  performance-profiling-tests:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up k6
        uses: grafana/setup-k6-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          tags: perf-profiling-tests:latest
          load: true  # Load the image into Docker

      - name: Read K6_CLOUD_API_TOKEN and set in CI Workflow
        env:
          K6_CLOUD_API_TOKEN: ${{ secrets.K6_CLOUD_API_TOKEN }}
        run: echo "K6_CLOUD_API_TOKEN=${K6_CLOUD_API_TOKEN}" >> $GITHUB_ENV

      - name: Run k6 Performance Test in Docker Container
        id: k6_test
        run: |
          docker run --rm -e K6_CLOUD_API_TOKEN=${{ secrets.K6_CLOUD_API_TOKEN }} perf-profiling-tests:latest > k6_output.txt
          cat k6_output.txt
          URL=$(grep -oP 'https://\S+' k6_output.txt)
          echo "GRAFANA_K6_TEST_REPORT_URL=$URL" >> $GITHUB_ENV

      - name: Add k6 URL as PR comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const url = process.env.GRAFANA_K6_TEST_REPORT_URL;
            const prNumber = context.payload.pull_request.number;
            const comment = `k6 Performance Test Report URL: ${url}`;

            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
